export const TAGS = {
  USERS: 'Users',
  PRODUCE: 'Produce',
  ORDERS: 'Orders',
  SUBSCRIPTIONS: 'Subscriptions',
  AUTH: 'Authentication',
  SELLERS: 'Sellers',
  BUYERS: 'Buyers',
  CHECKOUT: 'Checkout',
  MESSAGING: 'Messaging',
  AVAILABILITY: 'Availability',
  STRIPE: 'Stripe',
  CART: 'Cart',
  CONTACT: 'Contact',
  REVIEWS: 'Reviews',
  UPLOAD: 'Upload',
  GROWERS: 'Growers',
  SOURCE_MAP: 'SourceMap',
} as const;
