import { eq, inArray } from 'drizzle-orm';

import { db as defaultDb } from '../db/index.js';
import { fcmTokens } from '../db/schema.js';
import type { DbClient } from '../db/types.js';

export const fcmRepository = {
  db: defaultDb as unknown as DbClient,

  /**
   * Updates the database instance used by the repository.
   * @param newDb - The new database connection or mock instance
   */
  setDb(newDb: DbClient) {
    this.db = newDb;
  },

  /**
   * Updates/Upserts a user's Firebase Cloud Messaging token.
   * @param id - The unique user ID
   * @param token - The FCM token generated by the client
   * @param platform - The platform identifier (e.g., ios, android, web)
   */
  async upsertToken(id: string, token: string, platform: string): Promise<void> {
    await this.db
      .insert(fcmTokens)
      .values({
        userId: id,
        token,
        platform,
      })
      .onConflictDoUpdate({
        target: fcmTokens.token,
        set: { userId: id, platform }, // Reassigns user if account switches on same device
      });
  },

  /**
   * Fetches all tokens associated with a user.
   * @param userId - The user ID
   * @returns The tokens associated with the user ID
   */
  async getTokensByUserId(userId: string) {
    return await this.db.select().from(fcmTokens).where(eq(fcmTokens.userId, userId));
  },

  /**
   * Deletes multiple tokens at once.
   * Useful for cleaning up "Unregistered" tokens returned by Firebase.
   * @param tokens - An array of token IDs
   */
  async deleteTokens(tokens: string[]) {
    if (tokens.length === 0) return;
    await this.db.delete(fcmTokens).where(inArray(fcmTokens.token, tokens));
  },
};
