import { eq, type SQL, sql } from 'drizzle-orm';

import { db as defaultDb } from '../db/index.js';
import { fcmTokens, users } from '../db/schema.js';
import type { DbClient, User } from '../db/types.js';
import type { UpdateUserPayload } from '../schemas/user.schema.js';

export const userRepository = {
  db: defaultDb as unknown as DbClient,

  /**
   * Updates the database instance used by the repository.
   * @param newDb - The new database connection or mock instance
   */
  setDb(newDb: DbClient) {
    this.db = newDb;
  },

  /**
   * Retrieves a user from the database by their email address.
   * @param email - The unique email address to search for
   * @returns The user object if found, otherwise null
   */
  async findByEmail(email: string): Promise<User | null> {
    const [user] = await this.db.select().from(users).where(eq(users.email, email)).limit(1);

    return user ?? null;
  },

  /**
   * Retrieves a user from the database by their ID.
   * @param id - The unique user ID to search for
   * @returns The user object if found, otherwise null
   */
  async findById(id: string): Promise<User | null> {
    const [user] = await this.db.select().from(users).where(eq(users.id, id)).limit(1);
    return user ?? null;
  },

  /**
   * Updates a user's profile information by their ID.
   * @param id - The unique user ID to update
   * @param data - The update payload (handles extracting lat/lng to a PostGIS point)
   * @returns The updated user object if found, otherwise null
   */
  async updateById(id: string, data: UpdateUserPayload): Promise<User | null> {
    type UpdateSchema = Partial<typeof users.$inferInsert>;
    const updatePayload: { [K in keyof UpdateSchema]: UpdateSchema[K] | SQL } = {};

    if (data.name !== undefined) updatePayload.name = data.name;
    if (data.address !== undefined) updatePayload.address = data.address;
    if (data.deliveryRangeMiles !== undefined) {
      updatePayload.deliveryRangeMiles = data.deliveryRangeMiles.toString();
    }

    if (data.lat !== undefined && data.lng !== undefined) {
      updatePayload.location = sql`ST_SetSRID(ST_MakePoint(${data.lng}, ${data.lat}), 4326)`;
    }

    updatePayload.updatedAt = sql`now()`;

    const [updatedUser] = await this.db
      .update(users)
      .set(updatePayload)
      .where(eq(users.id, id))
      .returning();

    return updatedUser ?? null;
  },

  /**
   * Updates/Upserts a user's Firebase Cloud Messaging token.
   * @param id - The unique user ID
   * @param token - The FCM token generated by the client
   * @param platform - The platform identifier (e.g., ios, android, web)
   */
  async updateFcmToken(id: string, token: string, platform: string): Promise<void> {
    await this.db
      .insert(fcmTokens)
      .values({
        userId: id,
        token,
        platform,
      })
      .onConflictDoUpdate({
        target: fcmTokens.token,
        set: { userId: id, platform }, // Reassigns user if account switches on same device
      });
  },

  /**
   * Updates a user's internal Stripe Account ID.
   * @param id - The unique user ID
   * @param stripeAccountId - The generated Stripe Account ID
   * @returns The updated user object if found, otherwise null
   */
  async updateStripeAccountId(id: string, stripeAccountId: string): Promise<User | null> {
    const [updatedUser] = await this.db
      .update(users)
      .set({
        stripeAccountId,
        updatedAt: sql`now()`,
      })
      .where(eq(users.id, id))
      .returning();

    return updatedUser ?? null;
  },
};
